# Generated by Django 5.0.3 on 2024-04-06 05:37

import ckeditor.fields
import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Tech', 'Tech'), ('Programming', 'Programming'), ('Web Development', 'Web Development'), ('Malware Development', 'Malware Development'), ('Malware Analysis', 'Malware Analysis'), ('Reverse Engineering', 'Reverse Engineering'), ('Hardware', 'Hardware'), ('Self Learning', 'Self learning')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=255, null=True)),
                ('category', models.CharField(choices=[('Application', 'Application'), ('Malware', 'Malware'), ('Hardware', 'Hardware'), ('Other', 'Other')], max_length=50, null=True)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('thumbnail', models.ImageField(null=True, upload_to='')),
                ('date', models.DateTimeField(default=datetime.datetime.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_blog',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
                ('date', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('tags', models.ManyToManyField(to='app.tag')),
            ],
        ),
    ]
